apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  replicas: 1
  selector:
    app: lobsters
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:1.0.0
          env:
            - name: DATABASE_URL
              value: "mysql2://lobster:linux@mysql.default.svc.cluster.local:3306/lobster"
          ports:
            - containerPort: 3000
              protocol: TCP
