apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: lobsters-db-schema-load
spec:
  selector:
    matchLabels:
      task: db-schema-load
  template:
    metadata:
      name: lobsters-db-schema-load
      labels:
        task: db-schema-load
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:1.0.0
          env:
            - name: DATABASE_URL
              value: "mysql2://lobster:linux@10.31.240.125:3306/lobster"
          command:
            - "/usr/local/bundle/bin/rake"
            - "db:schema:load"
      restartPolicy: Never
