apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "ghost"
        version: "0.7.8"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:1.7.9"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
        - name: "ghost"
          image: "kelseyhightower/ghost:0.7.8"
          env:
            - name: "NODE_ENV"
              value: "production"
            - name: "GHOST_CONFIG"
              value: "/etc/ghost/config.js"
          volumeMounts:
            - name: "ghost"
              mountPath: "/etc/ghost"
            - name: "ghost-tls"
              mountPath: "/etc/ghost/ssl"
      volumes:
        - name: "ghost-tls"
          secret:
            secretName: "ghost-tls"
        - name: "nginx-conf"
          configMap:
            name: "nginx-ghost"
            items:
              - key: "ghost.conf"
                path: "ghost.conf"
        - name: "ghost"
          secret:
            secretName: "ghost"
