apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost
    version: 0.7.8-4
  name: ghost
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ghost
    version: 0.7.8-4
  sessionAffinity: None
  type: NodePort
